name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build with Buildozer
      uses: artem-ryabov/buildozer-action@v1.0.3
      with:
        work-dir: ./
        buildozer-version: stable

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: stockctrl-scanner-apk
        path: bin/*.apk
        retention-days: 30
